[package]
name = "wobi"
authors = ["Nikita Moskaliov <nikwit10@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
regex = "1.11.1"
serde = { version = "1.0.213", features = ["derive"] }
toml = "0.8.19"
